### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by maxclaus** [maxcnunes/monitor-api#1]
- [x] send email notifications
- [x] delete target
- [x] delete all children tracks on deleting parent target
- [x] websocket on dashboard
- [ ] allow select polling interval for each target
